name: BetterNick
version: 1.0.0
main: Luthfi\BetterNick\BetterNick
api: 5.0.0
commands:
  nick:
    description: Manage Nicknames
    usage: |
      /nick <name>
      /unnick
      /randomnick
    permission: betternick.use
  unnick:
    description: Reset your nickname
    usage: /unnick
    permission: betternick.use
  randomnick:
    description: Get a random nickname
    usage: /randomnick
    permission: betternick.use

permissions:
  betternick.use:
    description: Allow use nick command
    default: true
  betternick.admin:
    description: Allow managing other player nicknames
    default: op
