# Nickname Cooldown (in second)
cooldown: 30

# Maximum allowed nickname length
max_length: 16

# Format for random nicknames (use {random} for the number)
random_format: "User{random}"

# List of banned words
blacklist:
  - "admin"
  - "owner"

# Auto-Nick
auto_nick_enabled: false
auto_nick_format: "User{random}"

# Similarity check
max_similarity: 3

# don't modify
nicknames: []
